# Generated by Django 4.2.7 on 2023-11-30 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gatunek', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Wytwornia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=60)),
                ('zalozyciel', models.CharField(max_length=100)),
                ('siedziba', models.CharField(max_length=60)),
                ('gatunek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklEP.gatunek')),
            ],
        ),
        migrations.CreateModel(
            name='Producent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=60)),
                ('nazwisko', models.CharField(max_length=60)),
                ('pseudonim', models.CharField(max_length=60)),
                ('pochodzenie', models.CharField(max_length=60)),
                ('gatunek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklEP.gatunek')),
                ('wytwornia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklEP.wytwornia')),
            ],
        ),
        migrations.CreateModel(
            name='Festiwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=150)),
                ('kraj', models.CharField(max_length=60)),
                ('gospodarz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklEP.producent')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(choices=[('SI', 'Singiel'), ('EP', 'Extended Play'), ('LP', 'LongPlay'), ('MX', 'Mixtape')], default='SI', max_length=2)),
                ('nazwa', models.CharField(max_length=60)),
                ('data_premiery', models.DateField()),
                ('ilosc_utworow', models.IntegerField()),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklEP.producent')),
                ('gatunek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklEP.gatunek')),
            ],
        ),
    ]
