# Generated by Django 4.2.7 on 2023-12-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklEP', '0002_remove_producent_wytwornia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['nazwa']},
        ),
        migrations.AlterModelOptions(
            name='festiwal',
            options={'ordering': ['nazwa']},
        ),
        migrations.AlterModelOptions(
            name='gatunek',
            options={'ordering': ['gatunek']},
        ),
        migrations.AlterModelOptions(
            name='producent',
            options={'ordering': ['pseudonim']},
        ),
        migrations.AlterModelOptions(
            name='wytwornia',
            options={'ordering': ['nazwa']},
        ),
    ]
